### ISSUE TITLE
Don't work, http error 500

### ISSUE THREAD

**Issue by YupCore** [ArttuKuikka/Y2Sharp#1]
maybe api links chaged and it don't work today

**Comment by ArttuKuikka** [comment]
Ok i will look into this later today

**Comment by YupCore** [comment]
and sometimes it's no errors, but file is empty and undeletable

**Comment by ArttuKuikka** [comment]
I tested the wpf example and at least that worked. You should try if you can download your video with the wpf example program, if that doesnt work there might be something wrong with your code or computer. Let me know if that helps.

**Comment by ArttuKuikka** [comment]
> and sometimes it's no errors, but file is empty and undeletable

Hmm thats very interesting. I will look into this more later

**Comment by YupCore** [comment]
Strangely, it's now working fine. My guess that it was y2mate servers or maybe my pc, but i don't know i tested it on android and it still hasn't been working

**Comment by ArttuKuikka** [comment]
I think you should check if you are inputting correct parameters but it could be just the y2mate servers. also if you are trying to download a live stream that doesn't work because of y2mate so that might be it
